components:
  - type: Label
    key: lb1
    text: "Label #1"
    unit: "lpm"
  - type: Label
    key: lb3
    unit: "m/s"
  - type: Label
    key: lb2
    text: "Flow Rate"
    unit: "m³/s"
  - type: Button
    key: key1
    text: "key1"
  - type: Button
    key: key2
    text: "key2"
